// karbeat_macros/src/lib.rs
use proc_macro::TokenStream;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{Data, DeriveInput, Expr, Fields, ItemStruct, Lit, Token, parse_macro_input};

/// Attribute macro that transforms a struct into a full synthesizer with common infrastructure.
///
/// # Usage
/// ```rust
/// #[karbeat_synth]
/// pub struct MySynth {
///     // Your synth-specific fields only
///     oscillators: [Oscillator; 3],
/// }
/// ```
///
/// # What it generates
///
/// **Injected fields:**
/// - `sample_rate: f32`
/// - `active_voices: Vec<SynthVoice>`
/// - `voice_buffer: Vec<f32>`
/// - `gain: f32`
/// - `filter: SynthFilter`
/// - `amp_envelope: AdsrSettings`
///
/// **Helper methods:**
/// - `base_set_parameter(&mut self, id: u32, value: f32) -> bool`
/// - `base_get_parameter(&self, id: u32) -> Option<f32>`
/// - `base_default_parameters() -> HashMap<u32, f32>`
/// - `base_reset(&mut self)`
///
/// **Standard parameter IDs (0-7):**
/// - 0: gain (0.0-1.0, default 0.5)
/// - 1: filter_cutoff (20.0-20000.0, default 2000.0)
/// - 2: filter_resonance (0.0-0.95, default 0.2)
/// - 3: filter_mode (0=LP, 1=HP, 2=BP, 3=Off)
/// - 4: env_attack (0.001-5.0, default 0.01)
/// - 5: env_decay (0.001-5.0, default 0.2)
/// - 6: env_sustain (0.0-1.0, default 0.7)
/// - 7: env_release (0.001-10.0, default 0.5)
#[proc_macro_attribute]
pub fn karbeat_synth(_args: TokenStream, input: TokenStream) -> TokenStream {
    let mut item_struct = parse_macro_input!(input as ItemStruct);
    let struct_name = &item_struct.ident;

    if let Fields::Named(ref mut fields) = item_struct.fields {
        // Inject common synth fields
        let common_fields: syn::FieldsNamed = syn::parse_quote!({
            pub sample_rate: f32,
            pub active_voices: Vec<SynthVoice>,
            pub voice_buffer: Vec<f32>,
            pub gain: f32,
            pub filter: SynthFilter,
            pub amp_envelope: AdsrSettings,
        });

        for field in common_fields.named {
            fields.named.push(field);
        }
    }

    // Generate the struct with common types and helper impl
    let expanded = quote! {
        // ============================================================
        // COMMON SYNTH TYPES (generated by #[karbeat_synth])
        // ============================================================

        /// Filter mode for the synthesizer
        #[derive(Clone, Copy, PartialEq, Debug)]
        pub enum FilterMode {
            LowPass = 0,
            HighPass = 1,
            BandPass = 2,
            Off = 3,
        }

        impl From<f32> for FilterMode {
            fn from(v: f32) -> Self {
                match v as u32 {
                    0 => FilterMode::LowPass,
                    1 => FilterMode::HighPass,
                    2 => FilterMode::BandPass,
                    _ => FilterMode::Off,
                }
            }
        }

        /// ADSR envelope settings
        #[derive(Clone, Copy, Debug)]
        pub struct AdsrSettings {
            pub attack: f32,  // Seconds
            pub decay: f32,   // Seconds
            pub sustain: f32, // 0.0 to 1.0
            pub release: f32, // Seconds
        }

        impl Default for AdsrSettings {
            fn default() -> Self {
                Self {
                    attack: 0.01,
                    decay: 0.2,
                    sustain: 0.7,
                    release: 0.5,
                }
            }
        }

        /// Envelope stage for voice processing
        #[derive(Clone, Copy, Debug, PartialEq)]
        pub enum EnvelopeStage {
            Attack,
            Decay,
            Sustain,
            Release,
            Idle,
        }

        /// State-variable filter for the synthesizer
        #[derive(Clone, Copy, Debug)]
        pub struct SynthFilter {
            pub cutoff: f32,    // Hz (20.0 - 20000.0)
            pub resonance: f32, // 0.0 to 0.95
            pub mode: FilterMode,
            // Internal state (Stereo)
            pub s1_l: f32,
            pub s2_l: f32,
            pub s1_r: f32,
            pub s2_r: f32,
        }

        impl Default for SynthFilter {
            fn default() -> Self {
                Self {
                    cutoff: 2000.0,
                    resonance: 0.2,
                    mode: FilterMode::LowPass,
                    s1_l: 0.0, s2_l: 0.0,
                    s1_r: 0.0, s2_r: 0.0,
                }
            }
        }

        impl SynthFilter {
            /// Reset filter state (call on reset/seek)
            pub fn reset(&mut self) {
                self.s1_l = 0.0; self.s2_l = 0.0;
                self.s1_r = 0.0; self.s2_r = 0.0;
            }

            /// Process a stereo interleaved buffer through the filter
            pub fn process(&mut self, buffer: &mut [f32], sample_rate: f32) {
                if self.mode == FilterMode::Off {
                    return;
                }

                let f = 2.0 * (std::f32::consts::PI * self.cutoff / sample_rate).sin();
                let q = self.resonance.clamp(0.0, 0.99);
                let damping = 2.0 * (1.0 - q);

                let frames = buffer.len() / 2;

                for i in 0..frames {
                    let l_idx = i * 2;
                    let r_idx = i * 2 + 1;

                    let in_l = buffer[l_idx];
                    let in_r = buffer[r_idx];

                    // Left channel
                    let lp_l = self.s2_l + f * self.s1_l;
                    let hp_l = in_l - lp_l - damping * self.s1_l;
                    let bp_l = f * hp_l + self.s1_l;
                    self.s1_l = bp_l;
                    self.s2_l = lp_l;

                    // Right channel
                    let lp_r = self.s2_r + f * self.s1_r;
                    let hp_r = in_r - lp_r - damping * self.s1_r;
                    let bp_r = f * hp_r + self.s1_r;
                    self.s1_r = bp_r;
                    self.s2_r = lp_r;

                    match self.mode {
                        FilterMode::LowPass => {
                            buffer[l_idx] = lp_l;
                            buffer[r_idx] = lp_r;
                        },
                        FilterMode::HighPass => {
                            buffer[l_idx] = hp_l;
                            buffer[r_idx] = hp_r;
                        },
                        FilterMode::BandPass => {
                            buffer[l_idx] = bp_l;
                            buffer[r_idx] = bp_r;
                        },
                        FilterMode::Off => {}
                    }
                }
            }
        }

        /// Voice state for polyphonic synthesis
        #[derive(Clone, Debug)]
        pub struct SynthVoice {
            pub note: u8,
            pub velocity: u8,
            pub phase: Vec<f32>,  // Phase for each oscillator (flexible count)

            // Envelope State
            pub env_stage: EnvelopeStage,
            pub env_level: f32,
            pub env_timer: f32,
            pub release_start_level: f32,

            pub is_active: bool,
        }

        impl SynthVoice {
            /// Create a new voice for a note-on event
            pub fn new(note: u8, velocity: u8, num_oscillators: usize) -> Self {
                Self {
                    note,
                    velocity,
                    phase: vec![0.0; num_oscillators],
                    env_stage: EnvelopeStage::Attack,
                    env_level: 0.0,
                    env_timer: 0.0,
                    release_start_level: 0.0,
                    is_active: true,
                }
            }

            /// Trigger release phase (note-off)
            pub fn release(&mut self) {
                if self.is_active && self.env_stage != EnvelopeStage::Release {
                    self.env_stage = EnvelopeStage::Release;
                    self.env_timer = 0.0;
                    self.release_start_level = self.env_level;
                }
            }

            /// Advance envelope by dt seconds, returns current level
            pub fn advance_envelope(&mut self, dt: f32, settings: &AdsrSettings) -> f32 {
                self.env_timer += dt;

                match self.env_stage {
                    EnvelopeStage::Attack => {
                        let rate = if settings.attack < 0.001 { 1000.0 } else { 1.0 / settings.attack };
                        self.env_level = (self.env_timer * rate).min(1.0);
                        if self.env_level >= 1.0 {
                            self.env_level = 1.0;
                            self.env_stage = EnvelopeStage::Decay;
                            self.env_timer = 0.0;
                        }
                    }
                    EnvelopeStage::Decay => {
                        let rate = if settings.decay < 0.001 { 1000.0 } else { 1.0 / settings.decay };
                        let progress = (self.env_timer * rate).min(1.0);
                        self.env_level = 1.0 - (progress * (1.0 - settings.sustain));
                        if progress >= 1.0 {
                            self.env_level = settings.sustain;
                            self.env_stage = EnvelopeStage::Sustain;
                        }
                    }
                    EnvelopeStage::Sustain => {
                        self.env_level = settings.sustain;
                    }
                    EnvelopeStage::Release => {
                        let rate = if settings.release < 0.001 { 1000.0 } else { 1.0 / settings.release };
                        let progress = (self.env_timer * rate).min(1.0);
                        self.env_level = self.release_start_level * (1.0 - progress);
                        if progress >= 1.0 {
                            self.env_level = 0.0;
                            self.is_active = false;
                            self.env_stage = EnvelopeStage::Idle;
                        }
                    }
                    EnvelopeStage::Idle => {
                        self.env_level = 0.0;
                        self.is_active = false;
                    }
                }

                self.env_level
            }
        }

        // ============================================================
        // THE STRUCT WITH INJECTED FIELDS
        // ============================================================
        #item_struct

        // ============================================================
        // HELPER IMPL (generated by #[karbeat_synth])
        // ============================================================
        impl #struct_name {
            /// Handle base parameters (IDs 0-7). Returns true if parameter was handled.
            pub fn base_set_parameter(&mut self, id: u32, value: f32) -> bool {
                match id {
                    0 => { self.gain = value.clamp(0.0, 1.0); true }
                    1 => { self.filter.cutoff = value.clamp(20.0, 20000.0); true }
                    2 => { self.filter.resonance = value.clamp(0.0, 0.95); true }
                    3 => { self.filter.mode = FilterMode::from(value); true }
                    4 => { self.amp_envelope.attack = value.clamp(0.001, 5.0); true }
                    5 => { self.amp_envelope.decay = value.clamp(0.001, 5.0); true }
                    6 => { self.amp_envelope.sustain = value.clamp(0.0, 1.0); true }
                    7 => { self.amp_envelope.release = value.clamp(0.001, 10.0); true }
                    _ => false
                }
            }

            /// Get base parameters (IDs 0-7). Returns Some if parameter was handled.
            pub fn base_get_parameter(&self, id: u32) -> Option<f32> {
                match id {
                    0 => Some(self.gain),
                    1 => Some(self.filter.cutoff),
                    2 => Some(self.filter.resonance),
                    3 => Some(self.filter.mode as u32 as f32),
                    4 => Some(self.amp_envelope.attack),
                    5 => Some(self.amp_envelope.decay),
                    6 => Some(self.amp_envelope.sustain),
                    7 => Some(self.amp_envelope.release),
                    _ => None
                }
            }

            /// Get default parameter values for base parameters (IDs 0-7)
            pub fn base_default_parameters() -> std::collections::HashMap<u32, f32> {
                let mut map = std::collections::HashMap::new();
                map.insert(0, 0.5);     // gain
                map.insert(1, 2000.0);  // filter_cutoff
                map.insert(2, 0.2);     // filter_resonance
                map.insert(3, 0.0);     // filter_mode (LowPass)
                map.insert(4, 0.01);    // env_attack
                map.insert(5, 0.2);     // env_decay
                map.insert(6, 0.7);     // env_sustain
                map.insert(7, 0.5);     // env_release
                map
            }

            /// Reset voices and filter state
            pub fn base_reset(&mut self) {
                self.active_voices.clear();
                self.filter.reset();
            }

            /// Apply filter and gain to a stereo buffer
            pub fn apply_filter_and_gain(&mut self, buffer: &mut [f32]) {
                self.filter.process(buffer, self.sample_rate);
                for sample in buffer.iter_mut() {
                    *sample *= self.gain;
                }
            }

            /// Cleanup inactive voices (call at end of process)
            pub fn cleanup_voices(&mut self) {
                self.active_voices.retain(|v| v.is_active);
            }
        }
    };

    expanded.into()
}

// ============================================================================
// Additional derive macro for custom parameters (optional)
// ============================================================================

/// Helper struct for parsing key=value pairs in #[param(...)]
struct ParamAttr {
    id: Option<u32>,
    default: Option<f32>,
    min: Option<f32>,
    max: Option<f32>,
}

impl Parse for ParamAttr {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut id = None;
        let mut default = None;
        let mut min = None;
        let mut max = None;

        let pairs: Punctuated<syn::MetaNameValue, Token![,]> = Punctuated::parse_terminated(input)?;

        for pair in pairs {
            let key = pair
                .path
                .get_ident()
                .ok_or_else(|| syn::Error::new_spanned(&pair.path, "expected identifier"))?
                .to_string();

            let value = &pair.value;

            match key.as_str() {
                "id" => {
                    if let Expr::Lit(expr_lit) = value {
                        if let Lit::Int(lit_int) = &expr_lit.lit {
                            id = Some(lit_int.base10_parse()?);
                        }
                    }
                }
                "default" => {
                    default = Some(parse_f32_expr(value)?);
                }
                "min" => {
                    min = Some(parse_f32_expr(value)?);
                }
                "max" => {
                    max = Some(parse_f32_expr(value)?);
                }
                _ => {}
            }
        }

        Ok(ParamAttr {
            id,
            default,
            min,
            max,
        })
    }
}

fn parse_f32_expr(expr: &Expr) -> syn::Result<f32> {
    match expr {
        Expr::Lit(expr_lit) => match &expr_lit.lit {
            Lit::Float(lit_float) => lit_float.base10_parse(),
            Lit::Int(lit_int) => {
                let val: i64 = lit_int.base10_parse()?;
                Ok(val as f32)
            }
            _ => Err(syn::Error::new_spanned(
                expr,
                "expected float or int literal",
            )),
        },
        Expr::Unary(unary) if matches!(unary.op, syn::UnOp::Neg(_)) => {
            let inner = parse_f32_expr(&unary.expr)?;
            Ok(-inner)
        }
        _ => Err(syn::Error::new_spanned(expr, "expected numeric literal")),
    }
}

/// Derive macro for generating parameter helper methods from #[param(...)] attributes.
/// Use for synth-specific parameters beyond the base set.
#[proc_macro_derive(KarbeatParams, attributes(param))]
pub fn derive_karbeat_params(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    let mut set_arms = Vec::new();
    let mut get_arms = Vec::new();
    let mut default_inserts = Vec::new();

    if let Data::Struct(data) = &input.data {
        if let Fields::Named(fields) = &data.fields {
            for field in &fields.named {
                let field_name = field.ident.as_ref().unwrap();

                for attr in &field.attrs {
                    if attr.path().is_ident("param") {
                        let param_attr: ParamAttr = match attr.parse_args() {
                            Ok(p) => p,
                            Err(_) => continue,
                        };

                        if let (Some(id), Some(default)) = (param_attr.id, param_attr.default) {
                            let set_logic =
                                if let (Some(min), Some(max)) = (param_attr.min, param_attr.max) {
                                    quote! { self.#field_name = value.clamp(#min, #max); }
                                } else {
                                    quote! { self.#field_name = value; }
                                };
                            set_arms.push(quote! { #id => { #set_logic } });
                            get_arms.push(quote! { #id => self.#field_name });
                            default_inserts.push(quote! { map.insert(#id, #default); });
                        }
                    }
                }
            }
        }
    }

    quote! {
        impl #name {
            pub fn auto_set_parameter(&mut self, id: u32, value: f32) {
                match id {
                    #(#set_arms,)*
                    _ => {}
                }
            }

            pub fn auto_get_parameter(&self, id: u32) -> f32 {
                match id {
                    #(#get_arms,)*
                    _ => 0.0
                }
            }

            pub fn auto_default_parameters(&self) -> std::collections::HashMap<u32, f32> {
                let mut map = std::collections::HashMap::new();
                #(#default_inserts)*
                map
            }
        }
    }
    .into()
}
