// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TransportState {
  final bool isPlaying;
  final bool isPatternPlaying;
  final bool isRecording;
  final bool isLooping;
  final int playheadPositionSamples;
  final int loopStartSamples;
  final int loopEndSamples;
  final double bpm;
  final (int, int) timeSignature;
  final int beatTracker;
  final int barTracker;

  const TransportState({
    required this.isPlaying,
    required this.isPatternPlaying,
    required this.isRecording,
    required this.isLooping,
    required this.playheadPositionSamples,
    required this.loopStartSamples,
    required this.loopEndSamples,
    required this.bpm,
    required this.timeSignature,
    required this.beatTracker,
    required this.barTracker,
  });

  @override
  int get hashCode =>
      isPlaying.hashCode ^
      isPatternPlaying.hashCode ^
      isRecording.hashCode ^
      isLooping.hashCode ^
      playheadPositionSamples.hashCode ^
      loopStartSamples.hashCode ^
      loopEndSamples.hashCode ^
      bpm.hashCode ^
      timeSignature.hashCode ^
      beatTracker.hashCode ^
      barTracker.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportState &&
          runtimeType == other.runtimeType &&
          isPlaying == other.isPlaying &&
          isPatternPlaying == other.isPatternPlaying &&
          isRecording == other.isRecording &&
          isLooping == other.isLooping &&
          playheadPositionSamples == other.playheadPositionSamples &&
          loopStartSamples == other.loopStartSamples &&
          loopEndSamples == other.loopEndSamples &&
          bpm == other.bpm &&
          timeSignature == other.timeSignature &&
          beatTracker == other.beatTracker &&
          barTracker == other.barTracker;
}
