// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Serializable project transport settings.
/// Runtime transport state (is_playing, playhead, etc.) lives in the AudioEngine.
class TransportState {
  final double bpm;
  final (int, int) timeSignature;

  const TransportState.raw({required this.bpm, required this.timeSignature});

  factory TransportState() =>
      RustLib.instance.api.crateCoreProjectTransportTransportStateNew();

  static TransportState newWithParam({
    required double bpm,
    required (int, int) timeSignature,
  }) =>
      RustLib.instance.api.crateCoreProjectTransportTransportStateNewWithParam(
        bpm: bpm,
        timeSignature: timeSignature,
      );

  @override
  int get hashCode => bpm.hashCode ^ timeSignature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportState &&
          runtimeType == other.runtimeType &&
          bpm == other.bpm &&
          timeSignature == other.timeSignature;
}
