// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AudioHardwareConfig {
  final String selectedInputDevice;
  final String selectedOutputDevice;
  final int sampleRate;
  final int bufferSize;
  final double cpuLoad;

  const AudioHardwareConfig({
    required this.selectedInputDevice,
    required this.selectedOutputDevice,
    required this.sampleRate,
    required this.bufferSize,
    required this.cpuLoad,
  });

  @override
  int get hashCode =>
      selectedInputDevice.hashCode ^
      selectedOutputDevice.hashCode ^
      sampleRate.hashCode ^
      bufferSize.hashCode ^
      cpuLoad.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioHardwareConfig &&
          runtimeType == other.runtimeType &&
          selectedInputDevice == other.selectedInputDevice &&
          selectedOutputDevice == other.selectedOutputDevice &&
          sampleRate == other.sampleRate &&
          bufferSize == other.bufferSize &&
          cpuLoad == other.cpuLoad;
}

class ProjectMetadata {
  final String name;
  final String author;
  final String version;
  final int createdAt;

  const ProjectMetadata({
    required this.name,
    required this.author,
    required this.version,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^ author.hashCode ^ version.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          version == other.version &&
          createdAt == other.createdAt;
}
