// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AudioHardwareConfig {
  final String selectedInputDevice;
  final String selectedOutputDevice;
  final int sampleRate;
  final int bufferSize;
  final double cpuLoad;

  const AudioHardwareConfig({
    required this.selectedInputDevice,
    required this.selectedOutputDevice,
    required this.sampleRate,
    required this.bufferSize,
    required this.cpuLoad,
  });

  @override
  int get hashCode =>
      selectedInputDevice.hashCode ^
      selectedOutputDevice.hashCode ^
      sampleRate.hashCode ^
      bufferSize.hashCode ^
      cpuLoad.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioHardwareConfig &&
          runtimeType == other.runtimeType &&
          selectedInputDevice == other.selectedInputDevice &&
          selectedOutputDevice == other.selectedOutputDevice &&
          sampleRate == other.sampleRate &&
          bufferSize == other.bufferSize &&
          cpuLoad == other.cpuLoad;
}

class ProjectMetadata {
  final String name;
  final String author;
  final String version;
  final int createdAt;

  const ProjectMetadata({
    required this.name,
    required this.author,
    required this.version,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^ author.hashCode ^ version.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          version == other.version &&
          createdAt == other.createdAt;
}

enum TrackType { audio, midi, automation }

class TransportState {
  final bool isPlaying;
  final bool isRecording;
  final bool isLooping;
  final int playheadPositionSamples;
  final int loopStartSamples;
  final int loopEndSamples;
  final double bpm;
  final (int, int) timeSignature;

  const TransportState({
    required this.isPlaying,
    required this.isRecording,
    required this.isLooping,
    required this.playheadPositionSamples,
    required this.loopStartSamples,
    required this.loopEndSamples,
    required this.bpm,
    required this.timeSignature,
  });

  @override
  int get hashCode =>
      isPlaying.hashCode ^
      isRecording.hashCode ^
      isLooping.hashCode ^
      playheadPositionSamples.hashCode ^
      loopStartSamples.hashCode ^
      loopEndSamples.hashCode ^
      bpm.hashCode ^
      timeSignature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportState &&
          runtimeType == other.runtimeType &&
          isPlaying == other.isPlaying &&
          isRecording == other.isRecording &&
          isLooping == other.isLooping &&
          playheadPositionSamples == other.playheadPositionSamples &&
          loopStartSamples == other.loopStartSamples &&
          loopEndSamples == other.loopEndSamples &&
          bpm == other.bpm &&
          timeSignature == other.timeSignature;
}
