// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ProjectMetadata {
  final String name;
  final String author;
  final String version;
  final int createdAt;
  final double bpm;
  final (int, int) timeSignature;

  const ProjectMetadata({
    required this.name,
    required this.author,
    required this.version,
    required this.createdAt,
    required this.bpm,
    required this.timeSignature,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      author.hashCode ^
      version.hashCode ^
      createdAt.hashCode ^
      bpm.hashCode ^
      timeSignature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          author == other.author &&
          version == other.version &&
          createdAt == other.createdAt &&
          bpm == other.bpm &&
          timeSignature == other.timeSignature;
}

enum TrackType { audio, midi, automation }

class TransportState {
  final bool isPlaying;
  final bool isRecording;
  final bool isLooping;
  final int playheadPositionSamples;
  final int loopStartSamples;
  final int loopEndSamples;

  const TransportState({
    required this.isPlaying,
    required this.isRecording,
    required this.isLooping,
    required this.playheadPositionSamples,
    required this.loopStartSamples,
    required this.loopEndSamples,
  });

  @override
  int get hashCode =>
      isPlaying.hashCode ^
      isRecording.hashCode ^
      isLooping.hashCode ^
      playheadPositionSamples.hashCode ^
      loopStartSamples.hashCode ^
      loopEndSamples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportState &&
          runtimeType == other.runtimeType &&
          isPlaying == other.isPlaying &&
          isRecording == other.isRecording &&
          isLooping == other.isLooping &&
          playheadPositionSamples == other.playheadPositionSamples &&
          loopStartSamples == other.loopStartSamples &&
          loopEndSamples == other.loopEndSamples;
}
