// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PlaybackPosition {
  final int samples;
  final int beat;
  final int bar;
  final double tempo;
  final int sampleRate;

  const PlaybackPosition({
    required this.samples,
    required this.beat,
    required this.bar,
    required this.tempo,
    required this.sampleRate,
  });

  @override
  int get hashCode =>
      samples.hashCode ^
      beat.hashCode ^
      bar.hashCode ^
      tempo.hashCode ^
      sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackPosition &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          beat == other.beat &&
          bar == other.bar &&
          tempo == other.tempo &&
          sampleRate == other.sampleRate;
}
