// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Transport feedback struct sent from the audio thread to Flutter.
/// This is the single source of truth for all runtime transport state.
class TransportFeedback {
  final int samples;
  final int beat;
  final int bar;
  final double tempo;
  final int sampleRate;
  final bool isPlaying;
  final bool isLooping;
  final bool isRecording;
  final bool isPatternPlaying;
  final bool isPatternMode;
  final int patternSamples;
  final int patternBeat;
  final int patternBar;

  const TransportFeedback({
    required this.samples,
    required this.beat,
    required this.bar,
    required this.tempo,
    required this.sampleRate,
    required this.isPlaying,
    required this.isLooping,
    required this.isRecording,
    required this.isPatternPlaying,
    required this.isPatternMode,
    required this.patternSamples,
    required this.patternBeat,
    required this.patternBar,
  });

  @override
  int get hashCode =>
      samples.hashCode ^
      beat.hashCode ^
      bar.hashCode ^
      tempo.hashCode ^
      sampleRate.hashCode ^
      isPlaying.hashCode ^
      isLooping.hashCode ^
      isRecording.hashCode ^
      isPatternPlaying.hashCode ^
      isPatternMode.hashCode ^
      patternSamples.hashCode ^
      patternBeat.hashCode ^
      patternBar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportFeedback &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          beat == other.beat &&
          bar == other.bar &&
          tempo == other.tempo &&
          sampleRate == other.sampleRate &&
          isPlaying == other.isPlaying &&
          isLooping == other.isLooping &&
          isRecording == other.isRecording &&
          isPatternPlaying == other.isPatternPlaying &&
          isPatternMode == other.isPatternMode &&
          patternSamples == other.patternSamples &&
          patternBeat == other.patternBeat &&
          patternBar == other.patternBar;
}
