// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/project.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'project.dart';

Future<AudioWaveformUiForAudioProperties?> getAudioProperties({
  required int id,
}) => RustLib.instance.api.crateApiAudioGetAudioProperties(id: id);

Future<void> playSourcePreview({required int id}) =>
    RustLib.instance.api.crateApiAudioPlaySourcePreview(id: id);

Future<void> stopAllPreviews() =>
    RustLib.instance.api.crateApiAudioStopAllPreviews();

Future<AudioHardwareConfig> getAudioConfig() =>
    RustLib.instance.api.crateApiAudioGetAudioConfig();
