// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mixer.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UiEffectInstance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `into`, `into`

/// ======================================
/// GETTERS
/// ======================================
/// **GETTER: Fetch the mixer state**
Future<UiMixerState> getMixerState() =>
    RustLib.instance.api.crateApiMixerGetMixerState();

/// **GETTER: Fetch a specific mixer channel**
Future<UiMixerChannel> getMixerChannel({required int trackId}) =>
    RustLib.instance.api.crateApiMixerGetMixerChannel(trackId: trackId);

/// **GETTER: Fetch the master bus**
Future<UiMixerChannel> getMasterBus() =>
    RustLib.instance.api.crateApiMixerGetMasterBus();

/// **GETTER: Fetch all buses**
Future<List<UiBus>> getBuses() => RustLib.instance.api.crateApiMixerGetBuses();

/// **GETTER: Fetch the routing matrix**
Future<List<UiRoutingConnection>> getRoutingMatrix() =>
    RustLib.instance.api.crateApiMixerGetRoutingMatrix();

Future<void> setMasterBusParams({required List<UiMixerChannelParams> params}) =>
    RustLib.instance.api.crateApiMixerSetMasterBusParams(params: params);

Future<void> setMixerChannelParams({
  required int trackId,
  required List<UiMixerChannelParams> params,
}) => RustLib.instance.api.crateApiMixerSetMixerChannelParams(
  trackId: trackId,
  params: params,
);

/// Add an effect to a mixer channel by its registry ID (preferred method).
Future<void> addEffectToMixerChannelById({
  required int trackId,
  required int registryId,
}) => RustLib.instance.api.crateApiMixerAddEffectToMixerChannelById(
  trackId: trackId,
  registryId: registryId,
);

/// Add an effect to a mixer channel by name (backwards compatible).
Future<void> addEffectToMixerChannel({
  required int trackId,
  required String effectName,
}) => RustLib.instance.api.crateApiMixerAddEffectToMixerChannel(
  trackId: trackId,
  effectName: effectName,
);

Future<void> addEffectToMasterBus({required int registryId}) => RustLib
    .instance
    .api
    .crateApiMixerAddEffectToMasterBus(registryId: registryId);

/// Create a new mixer bus and return its ID.
Future<int> createBus({required String name}) =>
    RustLib.instance.api.crateApiMixerCreateBus(name: name);

/// Delete a mixer bus.
Future<void> deleteBus({required int busId}) =>
    RustLib.instance.api.crateApiMixerDeleteBus(busId: busId);

/// Set bus channel parameters (volume, pan, mute).
Future<void> setBusParams({
  required int busId,
  required List<UiMixerChannelParams> params,
}) => RustLib.instance.api.crateApiMixerSetBusParams(
  busId: busId,
  params: params,
);

/// Set routing: source → destination with send level.
/// source_type: 0=Track, 1=Bus
/// dest_type: 1=Bus, 2=Master
Future<void> setRouting({
  required int sourceType,
  required int sourceId,
  required int destType,
  required int destId,
  required double sendLevel,
  required bool isSend,
}) => RustLib.instance.api.crateApiMixerSetRouting(
  sourceType: sourceType,
  sourceId: sourceId,
  destType: destType,
  destId: destId,
  sendLevel: sendLevel,
  isSend: isSend,
);

/// Remove a routing connection.
Future<void> removeRouting({
  required int sourceType,
  required int sourceId,
  required int destType,
  required int destId,
  required bool isSend,
}) => RustLib.instance.api.crateApiMixerRemoveRouting(
  sourceType: sourceType,
  sourceId: sourceId,
  destType: destType,
  destId: destId,
  isSend: isSend,
);

/// UI representation of a mixer bus.
class UiBus {
  final int id;
  final String name;
  final UiMixerChannel channel;

  const UiBus({required this.id, required this.name, required this.channel});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ channel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiBus &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          channel == other.channel;
}

/// ======================================
/// Type Definitions
/// ======================================
/// UI representation of a mixer channel.
class UiMixerChannel {
  final double volume;
  final double pan;
  final bool mute;
  final bool solo;
  final bool invertedPhase;

  /// List of effect IDs. UI does not need the heavy data object of effect instance
  final Uint32List effects;

  const UiMixerChannel({
    required this.volume,
    required this.pan,
    required this.mute,
    required this.solo,
    required this.invertedPhase,
    required this.effects,
  });

  @override
  int get hashCode =>
      volume.hashCode ^
      pan.hashCode ^
      mute.hashCode ^
      solo.hashCode ^
      invertedPhase.hashCode ^
      effects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerChannel &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          pan == other.pan &&
          mute == other.mute &&
          solo == other.solo &&
          invertedPhase == other.invertedPhase &&
          effects == other.effects;
}

@freezed
sealed class UiMixerChannelParams with _$UiMixerChannelParams {
  const UiMixerChannelParams._();

  const factory UiMixerChannelParams.volume(double field0) =
      UiMixerChannelParams_Volume;
  const factory UiMixerChannelParams.pan(double field0) =
      UiMixerChannelParams_Pan;
  const factory UiMixerChannelParams.mute(bool field0) =
      UiMixerChannelParams_Mute;
  const factory UiMixerChannelParams.invertedPhase(bool field0) =
      UiMixerChannelParams_InvertedPhase;
}

/// UI representation of the mixer state.
class UiMixerState {
  final Map<int, UiMixerChannel> channels;
  final UiMixerChannel masterBus;
  final List<UiBus> buses;
  final List<UiRoutingConnection> routing;

  const UiMixerState({
    required this.channels,
    required this.masterBus,
    required this.buses,
    required this.routing,
  });

  @override
  int get hashCode =>
      channels.hashCode ^
      masterBus.hashCode ^
      buses.hashCode ^
      routing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerState &&
          runtimeType == other.runtimeType &&
          channels == other.channels &&
          masterBus == other.masterBus &&
          buses == other.buses &&
          routing == other.routing;
}

/// UI representation of a routing connection.
class UiRoutingConnection {
  /// 0=Track, 1=Bus, 2=Master
  final int sourceType;
  final int sourceId;

  /// 0=Track, 1=Bus, 2=Master
  final int destType;
  final int destId;
  final double sendLevel;
  final bool isSend;

  const UiRoutingConnection({
    required this.sourceType,
    required this.sourceId,
    required this.destType,
    required this.destId,
    required this.sendLevel,
    required this.isSend,
  });

  @override
  int get hashCode =>
      sourceType.hashCode ^
      sourceId.hashCode ^
      destType.hashCode ^
      destId.hashCode ^
      sendLevel.hashCode ^
      isSend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiRoutingConnection &&
          runtimeType == other.runtimeType &&
          sourceType == other.sourceType &&
          sourceId == other.sourceId &&
          destType == other.destType &&
          destId == other.destId &&
          sendLevel == other.sendLevel &&
          isSend == other.isSend;
}
