// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mixer.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UiEffectInstance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `into`, `into`

/// ======================================
/// GETTERS
/// ======================================
/// **GETTER: Fetch the mixer state**
///
/// Does not throw error. panic if the app state lock is poisoned
Future<UiMixerState> getMixerState() =>
    RustLib.instance.api.crateApiMixerGetMixerState();

/// **GETTER: Fetch a specific mixer channel**
///
/// Throws error if the channel is not found
Future<UiMixerChannel> getMixerChannel({required int trackId}) =>
    RustLib.instance.api.crateApiMixerGetMixerChannel(trackId: trackId);

/// **GETTER: Fetch the master bus**
///
/// Does not throw error. panic if the app state lock is poisoned
Future<UiMixerChannel> getMasterBus() =>
    RustLib.instance.api.crateApiMixerGetMasterBus();

Future<void> setMasterBusParams({required List<UiMixerChannelParams> params}) =>
    RustLib.instance.api.crateApiMixerSetMasterBusParams(params: params);

Future<void> setMixerChannelParams({
  required int trackId,
  required List<UiMixerChannelParams> params,
}) => RustLib.instance.api.crateApiMixerSetMixerChannelParams(
  trackId: trackId,
  params: params,
);

/// Add an effect to a mixer channel by its registry ID (preferred method).
Future<void> addEffectToMixerChannelById({
  required int trackId,
  required int registryId,
}) => RustLib.instance.api.crateApiMixerAddEffectToMixerChannelById(
  trackId: trackId,
  registryId: registryId,
);

/// Add an effect to a mixer channel by name (backwards compatible).
Future<void> addEffectToMixerChannel({
  required int trackId,
  required String effectName,
}) => RustLib.instance.api.crateApiMixerAddEffectToMixerChannel(
  trackId: trackId,
  effectName: effectName,
);

/// ======================================
/// Type Definitions
/// ======================================
/// UI representation of a mixer channel.
class UiMixerChannel {
  final double volume;
  final double pan;
  final bool mute;
  final bool solo;
  final bool invertedPhase;

  /// List of effect IDs. UI does not need the heavy data object of effect instance
  final Uint32List effects;

  const UiMixerChannel({
    required this.volume,
    required this.pan,
    required this.mute,
    required this.solo,
    required this.invertedPhase,
    required this.effects,
  });

  @override
  int get hashCode =>
      volume.hashCode ^
      pan.hashCode ^
      mute.hashCode ^
      solo.hashCode ^
      invertedPhase.hashCode ^
      effects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerChannel &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          pan == other.pan &&
          mute == other.mute &&
          solo == other.solo &&
          invertedPhase == other.invertedPhase &&
          effects == other.effects;
}

@freezed
sealed class UiMixerChannelParams with _$UiMixerChannelParams {
  const UiMixerChannelParams._();

  const factory UiMixerChannelParams.volume(double field0) =
      UiMixerChannelParams_Volume;
  const factory UiMixerChannelParams.pan(double field0) =
      UiMixerChannelParams_Pan;
  const factory UiMixerChannelParams.mute(bool field0) =
      UiMixerChannelParams_Mute;
  const factory UiMixerChannelParams.invertedPhase(bool field0) =
      UiMixerChannelParams_InvertedPhase;
}

/// UI representation of the mixer state.
class UiMixerState {
  final Map<int, UiMixerChannel> channels;
  final UiMixerChannel masterBus;

  const UiMixerState({required this.channels, required this.masterBus});

  @override
  int get hashCode => channels.hashCode ^ masterBus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiMixerState &&
          runtimeType == other.runtimeType &&
          channels == other.channels &&
          masterBus == other.masterBus;
}
