// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

Future<UiPattern> getPattern({required int patternId}) =>
    RustLib.instance.api.crateApiPatternGetPattern(patternId: patternId);

Future<Map<int, UiPattern>> getPatterns() =>
    RustLib.instance.api.crateApiPatternGetPatterns();

Future<UiNote> addNote({
  required int patternId,
  required int key,
  required int startTick,
  int? duration,
}) => RustLib.instance.api.crateApiPatternAddNote(
  patternId: patternId,
  key: key,
  startTick: startTick,
  duration: duration,
);

Future<UiNote> deleteNote({required int patternId, required int index}) =>
    RustLib.instance.api.crateApiPatternDeleteNote(
      patternId: patternId,
      index: index,
    );

Future<UiNote> resizeNote({
  required int patternId,
  required int noteIndex,
  required int newDuration,
}) => RustLib.instance.api.crateApiPatternResizeNote(
  patternId: patternId,
  noteIndex: noteIndex,
  newDuration: newDuration,
);

Future<UiNote> moveNote({
  required int patternId,
  required int index,
  required int newStartTick,
  required int newKey,
}) => RustLib.instance.api.crateApiPatternMoveNote(
  patternId: patternId,
  index: index,
  newStartTick: newStartTick,
  newKey: newKey,
);

Future<UiNote> changeNoteParams({
  required int patternId,
  required int noteIndex,
  int? velocity,
  double? probability,
  int? microOffset,
  bool? mute,
}) => RustLib.instance.api.crateApiPatternChangeNoteParams(
  patternId: patternId,
  noteIndex: noteIndex,
  velocity: velocity,
  probability: probability,
  microOffset: microOffset,
  mute: mute,
);

class UiNote {
  final int startTick;
  final int duration;
  final int key;
  final int velocity;
  final double probability;
  final int microOffset;
  final bool mute;

  const UiNote({
    required this.startTick,
    required this.duration,
    required this.key,
    required this.velocity,
    required this.probability,
    required this.microOffset,
    required this.mute,
  });

  @override
  int get hashCode =>
      startTick.hashCode ^
      duration.hashCode ^
      key.hashCode ^
      velocity.hashCode ^
      probability.hashCode ^
      microOffset.hashCode ^
      mute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiNote &&
          runtimeType == other.runtimeType &&
          startTick == other.startTick &&
          duration == other.duration &&
          key == other.key &&
          velocity == other.velocity &&
          probability == other.probability &&
          microOffset == other.microOffset &&
          mute == other.mute;
}

class UiPattern {
  final int id;
  final String name;
  final int lengthTicks;
  final List<UiNote> notes;

  const UiPattern({
    required this.id,
    required this.name,
    required this.lengthTicks,
    required this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ lengthTicks.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPattern &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          lengthTicks == other.lengthTicks &&
          notes == other.notes;
}
