// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mixer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'project.dart';
part 'plugin.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `hash`

/// Get all available generators in Plugin Registry (names only, backwards compatible)
Future<List<String>> getAvailableGenerators() =>
    RustLib.instance.api.crateApiPluginGetAvailableGenerators();

/// Get all available effects in Plugin Registry (names only, backwards compatible)
Future<List<String>> getAvailableEffects() =>
    RustLib.instance.api.crateApiPluginGetAvailableEffects();

/// Get all available generators with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableGeneratorsWithIds() =>
    RustLib.instance.api.crateApiPluginGetAvailableGeneratorsWithIds();

/// Get all available effects with their registry IDs (preferred for UI)
Future<List<UiPluginInfo>> getAvailableEffectsWithIds() =>
    RustLib.instance.api.crateApiPluginGetAvailableEffectsWithIds();

/// Get a single generator state from the Generator Pool
Future<UiGeneratorInstance> getGenerator({required int generatorId}) =>
    RustLib.instance.api.crateApiPluginGetGenerator(generatorId: generatorId);

Future<UiEffectInstance> getEffect({
  required int trackId,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffect(
  trackId: trackId,
  effectId: effectId,
);

Future<UiEffectInstance> getEffectFromMaster({required int effectId}) =>
    RustLib.instance.api.crateApiPluginGetEffectFromMaster(effectId: effectId);

Future<List<UiEffectInstance>> getEffectsFromTrack({required int trackId}) =>
    RustLib.instance.api.crateApiPluginGetEffectsFromTrack(trackId: trackId);

Future<List<UiEffectInstance>> getMasterEffects() =>
    RustLib.instance.api.crateApiPluginGetMasterEffects();

/// Get parameter specifications for a generator plugin.
///
/// With the lock-free architecture, the live plugin instance runs on the audio thread
/// and cannot be accessed directly. Instead, we use the registry to query its static parameter specifications.
/// This is safe because parameter specs are static metadata that don't depend on state.
///
/// The returned specs include the current stored parameter values (from generator pool)
/// which may differ from defaults if the user has modified them.
Future<List<UiPluginParameter>> getGeneratorParameterSpecs({
  required int generatorId,
}) => RustLib.instance.api.crateApiPluginGetGeneratorParameterSpecs(
  generatorId: generatorId,
);

/// Set a parameter on a generator plugin.
///
/// This sends a command to the audio thread to update the parameter.
/// The parameter value is also stored in PluginInstance for persistence.
///
/// # Arguments
/// * `generator_id` - The ID of the generator
/// * `param_id` - The parameter ID
/// * `value` - The new value for the parameter
Future<void> setGeneratorParameter({
  required int generatorId,
  required int paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetGeneratorParameter(
  generatorId: generatorId,
  paramId: paramId,
  value: value,
);

/// Get a parameter value from a generator plugin.
///
/// Returns the stored parameter value for the given parameter ID.
/// With lock-free architecture, we read from the stored parameters,
/// not the live plugin on the audio thread.
Future<double> getGeneratorParameter({
  required int generatorId,
  required int paramId,
}) => RustLib.instance.api.crateApiPluginGetGeneratorParameter(
  generatorId: generatorId,
  paramId: paramId,
);

/// Request a parameter snapshot from the audio thread.
///
/// This sends a query to the audio thread, which will respond with the
/// current parameter values via the feedback channel. Use `poll_parameter_feedback`
/// to receive the response.
Future<void> queryGeneratorParameters({required int generatorId}) => RustLib
    .instance
    .api
    .crateApiPluginQueryGeneratorParameters(generatorId: generatorId);

/// Poll for parameter feedback from the audio thread.
///
/// This should be called periodically (e.g., in a timer or on parameter screen)
/// to receive parameter updates from the audio thread. Returns all pending
/// parameter snapshots.
Future<List<UiGeneratorParameterSnapshot>> pollGeneratorParameterFeedback() =>
    RustLib.instance.api.crateApiPluginPollGeneratorParameterFeedback();

/// Sync parameter values from audio thread to stored parameters.
///
/// Call this after `poll_parameter_feedback` to update the stored parameters
/// with the latest values from the audio thread.
Future<void> syncGeneratorParametersFromAudio({
  required List<UiGeneratorParameterSnapshot> snapshots,
}) => RustLib.instance.api.crateApiPluginSyncGeneratorParametersFromAudio(
  snapshots: snapshots,
);

Future<List<UiEffectParameterSnapshot>> pollEffectParameterFeedback() =>
    RustLib.instance.api.crateApiPluginPollEffectParameterFeedback();

Future<void> syncEffectParametersFromAudio({
  required List<UiEffectParameterSnapshot> snapshots,
}) => RustLib.instance.api.crateApiPluginSyncEffectParametersFromAudio(
  snapshots: snapshots,
);

/// Get parameter specifications for a track effect plugin.
///
/// Creates a temporary plugin instance from the registry to query static parameter
/// specs, then overlays the current stored parameter values.
Future<List<UiPluginParameter>> getEffectParameterSpecs({
  required UiEffectTarget target,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginGetEffectParameterSpecs(
  target: target,
  effectId: effectId,
);

/// Set a parameter on a track effect plugin.
///
/// Sends a command to the audio thread to update the parameter and also
/// persists the value in the stored PluginInstance parameters.
Future<void> setEffectParameter({
  required UiEffectTarget target,
  required int effectId,
  required int paramId,
  required double value,
}) => RustLib.instance.api.crateApiPluginSetEffectParameter(
  target: target,
  effectId: effectId,
  paramId: paramId,
  value: value,
);

/// Request a parameter snapshot from the audio thread for a track effect.
///
/// The audio thread will respond via AudioFeedback::EffectParameterSnapshot,
/// which can be polled using `poll_effect_parameter_feedback`.
Future<void> queryEffectParameters({
  required UiEffectTarget target,
  required int effectId,
}) => RustLib.instance.api.crateApiPluginQueryEffectParameters(
  target: target,
  effectId: effectId,
);

/// Compute the magnitude response curve for a parametric EQ effect on a track.
///
/// Creates a temporary plugin instance, applies stored parameters, and evaluates
/// the exact biquad transfer function at log-spaced frequency points.
Future<List<UiResponseCurvePoint>> getEqResponseCurve({
  required UiEffectTarget target,
  required int effectId,
  required int numPoints,
}) => RustLib.instance.api.crateApiPluginGetEqResponseCurve(
  target: target,
  effectId: effectId,
  numPoints: numPoints,
);

enum KarbeatPluginType { generator, effect }

class UiEffectParameterSnapshot {
  final UiEffectTarget target;
  final int effectId;
  final List<UiParameterValue> parameters;

  const UiEffectParameterSnapshot({
    required this.target,
    required this.effectId,
    required this.parameters,
  });

  @override
  int get hashCode => target.hashCode ^ effectId.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEffectParameterSnapshot &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          effectId == other.effectId &&
          parameters == other.parameters;
}

@freezed
sealed class UiEffectTarget with _$UiEffectTarget {
  const UiEffectTarget._();

  const factory UiEffectTarget.track(int field0) = UiEffectTarget_Track;
  const factory UiEffectTarget.master() = UiEffectTarget_Master;
  const factory UiEffectTarget.bus(int field0) = UiEffectTarget_Bus;
}

/// Parameter snapshot from the audio thread (DTO)
class UiGeneratorParameterSnapshot {
  final int generatorId;
  final List<UiParameterValue> parameters;

  const UiGeneratorParameterSnapshot({
    required this.generatorId,
    required this.parameters,
  });

  @override
  int get hashCode => generatorId.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiGeneratorParameterSnapshot &&
          runtimeType == other.runtimeType &&
          generatorId == other.generatorId &&
          parameters == other.parameters;
}

/// Parameter type enum for FRB
enum UiParameterType { float, int, bool, choice }

/// Single parameter value from the audio thread
class UiParameterValue {
  final int paramId;
  final double value;

  const UiParameterValue({required this.paramId, required this.value});

  @override
  int get hashCode => paramId.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiParameterValue &&
          runtimeType == other.runtimeType &&
          paramId == other.paramId &&
          value == other.value;
}

class UiPluginInfo {
  final int id;
  final String name;
  final KarbeatPluginType pluginType;

  const UiPluginInfo({
    required this.id,
    required this.name,
    required this.pluginType,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ pluginType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPluginInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          pluginType == other.pluginType;
}

/// Plugin parameter description for UI generation
class UiPluginParameter {
  final int id;
  final String name;
  final String group;
  final double value;
  final double min;
  final double max;
  final double defaultValue;
  final double step;
  final UiParameterType paramType;
  final List<String> choices;

  const UiPluginParameter({
    required this.id,
    required this.name,
    required this.group,
    required this.value,
    required this.min,
    required this.max,
    required this.defaultValue,
    required this.step,
    required this.paramType,
    required this.choices,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      group.hashCode ^
      value.hashCode ^
      min.hashCode ^
      max.hashCode ^
      defaultValue.hashCode ^
      step.hashCode ^
      paramType.hashCode ^
      choices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPluginParameter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          group == other.group &&
          value == other.value &&
          min == other.min &&
          max == other.max &&
          defaultValue == other.defaultValue &&
          step == other.step &&
          paramType == other.paramType &&
          choices == other.choices;
}

/// A point on the EQ response curve (DTO for FRB)
class UiResponseCurvePoint {
  final double frequency;
  final double magnitudeDb;

  const UiResponseCurvePoint({
    required this.frequency,
    required this.magnitudeDb,
  });

  @override
  int get hashCode => frequency.hashCode ^ magnitudeDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiResponseCurvePoint &&
          runtimeType == other.runtimeType &&
          frequency == other.frequency &&
          magnitudeDb == other.magnitudeDb;
}
