// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/project.dart';
import '../core/project/track.dart';
import '../core/project/transport.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'project.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioWaveformUiForClip`, `AudioWaveformUiForSourceList`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

/// Get the current project metadata state from the backend
Future<ProjectMetadata> getProjectMetadata() =>
    RustLib.instance.api.crateApiProjectGetProjectMetadata();

/// Get the transport state from the backend
Future<TransportState> getTransportState() =>
    RustLib.instance.api.crateApiProjectGetTransportState();

/// Get all audio waveform source list from the backend
Future<Map<int, AudioWaveformUiForAudioProperties>?> getAudioSourceList() =>
    RustLib.instance.api.crateApiProjectGetAudioSourceList();

/// Get generator list used in the project
Future<Map<int, UiGeneratorInstance>> getGeneratorList() =>
    RustLib.instance.api.crateApiProjectGetGeneratorList();

/// Add a new audio source to the project
///
/// ## Parameters:
/// - file_path: Path to the audio file to be added
Future<void> addAudioSource({required String filePath}) =>
    RustLib.instance.api.crateApiProjectAddAudioSource(filePath: filePath);

/// Add new track to the track list. Throws an error, so it must handled gracefully
Future<void> addNewTrack({required TrackType trackType}) =>
    RustLib.instance.api.crateApiProjectAddNewTrack(trackType: trackType);

/// Get all tracks on the session/project.
///
/// Returns Map<u32, UiTrack> upon success, and Error when it fails
Future<Map<int, UiTrack>> getTracks() =>
    RustLib.instance.api.crateApiProjectGetTracks();

/// Get the newest max sample index of the project
Future<int> getMaxSampleIndex() =>
    RustLib.instance.api.crateApiProjectGetMaxSampleIndex();

class AudioWaveformUiForAudioProperties {
  final Int8List previewBuffer;
  final String filePath;
  final String name;
  final int sampleRate;
  final int channels;
  final double duration;
  final int rootNote;
  final int fineTune;
  final int trimStart;
  final int trimEnd;
  final bool isLooping;
  final bool normalized;
  final bool muted;

  const AudioWaveformUiForAudioProperties({
    required this.previewBuffer,
    required this.filePath,
    required this.name,
    required this.sampleRate,
    required this.channels,
    required this.duration,
    required this.rootNote,
    required this.fineTune,
    required this.trimStart,
    required this.trimEnd,
    required this.isLooping,
    required this.normalized,
    required this.muted,
  });

  @override
  int get hashCode =>
      previewBuffer.hashCode ^
      filePath.hashCode ^
      name.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      duration.hashCode ^
      rootNote.hashCode ^
      fineTune.hashCode ^
      trimStart.hashCode ^
      trimEnd.hashCode ^
      isLooping.hashCode ^
      normalized.hashCode ^
      muted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioWaveformUiForAudioProperties &&
          runtimeType == other.runtimeType &&
          previewBuffer == other.previewBuffer &&
          filePath == other.filePath &&
          name == other.name &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          duration == other.duration &&
          rootNote == other.rootNote &&
          fineTune == other.fineTune &&
          trimStart == other.trimStart &&
          trimEnd == other.trimEnd &&
          isLooping == other.isLooping &&
          normalized == other.normalized &&
          muted == other.muted;
}

class UiClip {
  final String name;
  final int id;
  final int startTime;
  final UiClipSource source;
  final int offsetStart;
  final int loopLength;

  const UiClip({
    required this.name,
    required this.id,
    required this.startTime,
    required this.source,
    required this.offsetStart,
    required this.loopLength,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      id.hashCode ^
      startTime.hashCode ^
      source.hashCode ^
      offsetStart.hashCode ^
      loopLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiClip &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          id == other.id &&
          startTime == other.startTime &&
          source == other.source &&
          offsetStart == other.offsetStart &&
          loopLength == other.loopLength;
}

@freezed
sealed class UiClipSource with _$UiClipSource {
  const UiClipSource._();

  const factory UiClipSource.audio({required int sourceId}) =
      UiClipSource_Audio;
  const factory UiClipSource.midi({required int patternId}) = UiClipSource_Midi;
  const factory UiClipSource.none() = UiClipSource_None;
}

class UiGeneratorInstance {
  final int id;
  final String name;
  final Map<int, double> parameters;

  const UiGeneratorInstance({
    required this.id,
    required this.name,
    required this.parameters,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiGeneratorInstance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parameters == other.parameters;
}

class UiTrack {
  final int id;
  final String name;
  final TrackType trackType;
  final List<UiClip> clips;
  final int? generatorId;

  const UiTrack({
    required this.id,
    required this.name,
    required this.trackType,
    required this.clips,
    this.generatorId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      trackType.hashCode ^
      clips.hashCode ^
      generatorId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          trackType == other.trackType &&
          clips == other.clips &&
          generatorId == other.generatorId;
}
