// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/project.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'project.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

Future<UiProjectState?> getUiState() =>
    RustLib.instance.api.crateApiProjectGetUiState();

Future<TransportState> getTransportState() =>
    RustLib.instance.api.crateApiProjectGetTransportState();

Future<Map<int, AudioWaveformUiForSourceList>?> getSourceList() =>
    RustLib.instance.api.crateApiProjectGetSourceList();

Future<void> addAudioSource({required String filePath}) =>
    RustLib.instance.api.crateApiProjectAddAudioSource(filePath: filePath);

Future<void> addNewTrack({required String trackType}) =>
    RustLib.instance.api.crateApiProjectAddNewTrack(trackType: trackType);

Future<Map<int, UiTrack>> getTracks() =>
    RustLib.instance.api.crateApiProjectGetTracks();

class AudioWaveformUiForAudioProperties {
  final Float32List previewBuffer;
  final String filePath;
  final String name;
  final int sampleRate;
  final int channels;
  final double duration;
  final int rootNote;
  final int fineTune;
  final int trimStart;
  final int trimEnd;
  final bool isLooping;
  final bool normalized;
  final bool muted;

  const AudioWaveformUiForAudioProperties({
    required this.previewBuffer,
    required this.filePath,
    required this.name,
    required this.sampleRate,
    required this.channels,
    required this.duration,
    required this.rootNote,
    required this.fineTune,
    required this.trimStart,
    required this.trimEnd,
    required this.isLooping,
    required this.normalized,
    required this.muted,
  });

  @override
  int get hashCode =>
      previewBuffer.hashCode ^
      filePath.hashCode ^
      name.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      duration.hashCode ^
      rootNote.hashCode ^
      fineTune.hashCode ^
      trimStart.hashCode ^
      trimEnd.hashCode ^
      isLooping.hashCode ^
      normalized.hashCode ^
      muted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioWaveformUiForAudioProperties &&
          runtimeType == other.runtimeType &&
          previewBuffer == other.previewBuffer &&
          filePath == other.filePath &&
          name == other.name &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          duration == other.duration &&
          rootNote == other.rootNote &&
          fineTune == other.fineTune &&
          trimStart == other.trimStart &&
          trimEnd == other.trimEnd &&
          isLooping == other.isLooping &&
          normalized == other.normalized &&
          muted == other.muted;
}

class AudioWaveformUiForClip {
  final String name;
  final Float32List previewBuffer;

  const AudioWaveformUiForClip({
    required this.name,
    required this.previewBuffer,
  });

  @override
  int get hashCode => name.hashCode ^ previewBuffer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioWaveformUiForClip &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          previewBuffer == other.previewBuffer;
}

class AudioWaveformUiForSourceList {
  final String name;
  final bool muted;

  const AudioWaveformUiForSourceList({required this.name, required this.muted});

  @override
  int get hashCode => name.hashCode ^ muted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioWaveformUiForSourceList &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          muted == other.muted;
}

class UiClip {
  final String name;
  final int id;
  final int startTime;
  final UiClipSource source;
  final int offsetStart;
  final int loopLength;

  const UiClip({
    required this.name,
    required this.id,
    required this.startTime,
    required this.source,
    required this.offsetStart,
    required this.loopLength,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      id.hashCode ^
      startTime.hashCode ^
      source.hashCode ^
      offsetStart.hashCode ^
      loopLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiClip &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          id == other.id &&
          startTime == other.startTime &&
          source == other.source &&
          offsetStart == other.offsetStart &&
          loopLength == other.loopLength;
}

@freezed
sealed class UiClipSource with _$UiClipSource {
  const UiClipSource._();

  const factory UiClipSource.audio(AudioWaveformUiForClip field0) =
      UiClipSource_Audio;
  const factory UiClipSource.none() = UiClipSource_None;
}

class UiProjectState {
  final ProjectMetadata metadata;
  final List<UiTrack> tracks;

  const UiProjectState({required this.metadata, required this.tracks});

  @override
  int get hashCode => metadata.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiProjectState &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          tracks == other.tracks;
}

class UiTrack {
  final int id;
  final String name;
  final TrackType trackType;
  final List<UiClip> clips;

  const UiTrack({
    required this.id,
    required this.name,
    required this.trackType,
    required this.clips,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ trackType.hashCode ^ clips.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          trackType == other.trackType &&
          clips == other.clips;
}
