// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> updateSelectedClip({required int trackId, required int clipId}) =>
    RustLib.instance.api.crateApiSessionUpdateSelectedClip(
      trackId: trackId,
      clipId: clipId,
    );

Future<void> deselectClip() =>
    RustLib.instance.api.crateApiSessionDeselectClip();

Future<void> undo() => RustLib.instance.api.crateApiSessionUndo();

Future<void> redo() => RustLib.instance.api.crateApiSessionRedo();

Future<void> copyPatternNotes({
  required int patternId,
  required List<int> noteIds,
}) => RustLib.instance.api.crateApiSessionCopyPatternNotes(
  patternId: patternId,
  noteIds: noteIds,
);

Future<void> cutPatternNotes({
  required int patternId,
  required List<int> noteIds,
}) => RustLib.instance.api.crateApiSessionCutPatternNotes(
  patternId: patternId,
  noteIds: noteIds,
);

/// Paste: Reads clipboard, creates new notes, creates Batch Add action
Future<void> pastePatternNotes({
  required int targetPatternId,
  required int playheadTick,
}) => RustLib.instance.api.crateApiSessionPastePatternNotes(
  targetPatternId: targetPatternId,
  playheadTick: playheadTick,
);
