// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/project/track.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'project.dart';

Future<void> createClip({
  int? sourceId,
  required UiSourceType sourceType,
  required int trackId,
  required int startTime,
}) => RustLib.instance.api.crateApiTrackCreateClip(
  sourceId: sourceId,
  sourceType: sourceType,
  trackId: trackId,
  startTime: startTime,
);

Future<void> deleteClip({required int trackId, required int clipId}) => RustLib
    .instance
    .api
    .crateApiTrackDeleteClip(trackId: trackId, clipId: clipId);

/// Resize the clip. for default mode, it will only adjust
/// the start time and loop length of the clip
Future<void> resizeClip({
  required int trackId,
  required int clipId,
  required ResizeEdge edge,
  required int newTimeVal,
}) => RustLib.instance.api.crateApiTrackResizeClip(
  trackId: trackId,
  clipId: clipId,
  edge: edge,
  newTimeVal: newTimeVal,
);

Future<void> moveClip({
  required int sourceTrackId,
  required int clipId,
  required int newStartTime,
  int? newTrackId,
}) => RustLib.instance.api.crateApiTrackMoveClip(
  sourceTrackId: sourceTrackId,
  clipId: clipId,
  newStartTime: newStartTime,
  newTrackId: newTrackId,
);

/// Add a MIDI track with a generator by its registry ID (preferred method).
Future<void> addMidiTrackWithGeneratorId({required int registryId}) => RustLib
    .instance
    .api
    .crateApiTrackAddMidiTrackWithGeneratorId(registryId: registryId);

/// Add a MIDI track with a generator by name (backwards compatible).
Future<void> addMidiTrackWithGenerator({required String generatorName}) =>
    RustLib.instance.api.crateApiTrackAddMidiTrackWithGenerator(
      generatorName: generatorName,
    );

Future<UiClip> getClip({required int trackId, required int clipId}) =>
    RustLib.instance.api.crateApiTrackGetClip(trackId: trackId, clipId: clipId);

Future<UiTrack> getTrack({required int trackId}) =>
    RustLib.instance.api.crateApiTrackGetTrack(trackId: trackId);

/// move clips in batch
Future<void> moveClipBatch({
  required int sourceTrackId,
  required List<int> clipIds,
  required int deltaSamples,
  int? newTrackId,
}) => RustLib.instance.api.crateApiTrackMoveClipBatch(
  sourceTrackId: sourceTrackId,
  clipIds: clipIds,
  deltaSamples: deltaSamples,
  newTrackId: newTrackId,
);

/// Resize clips in batch by a delta amount
Future<void> resizeClipBatch({
  required int trackId,
  required List<int> clipIds,
  required ResizeEdge edge,
  required int deltaSamples,
}) => RustLib.instance.api.crateApiTrackResizeClipBatch(
  trackId: trackId,
  clipIds: clipIds,
  edge: edge,
  deltaSamples: deltaSamples,
);

/// Delete clips in batch
Future<void> deleteClipBatch({
  required int trackId,
  required List<int> clipIds,
}) => RustLib.instance.api.crateApiTrackDeleteClipBatch(
  trackId: trackId,
  clipIds: clipIds,
);

enum ResizeEdge { left, right }

enum UiSourceType { audio, midi }
