// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> createClip({
  required int sourceId,
  required UiSourceType sourceType,
  required int trackId,
  required int startTime,
}) => RustLib.instance.api.crateApiTrackCreateClip(
  sourceId: sourceId,
  sourceType: sourceType,
  trackId: trackId,
  startTime: startTime,
);

Future<void> deleteClip({required int trackId, required int clipId}) => RustLib
    .instance
    .api
    .crateApiTrackDeleteClip(trackId: trackId, clipId: clipId);

Future<void> resizeClip({
  required int trackId,
  required int clipId,
  required ResizeEdge edge,
  required int newTimeVal,
}) => RustLib.instance.api.crateApiTrackResizeClip(
  trackId: trackId,
  clipId: clipId,
  edge: edge,
  newTimeVal: newTimeVal,
);

enum ResizeEdge { left, right }

enum UiSourceType { audio, midi }
