// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> setPlaying({required bool val}) =>
    RustLib.instance.api.crateApiTransportSetPlaying(val: val);

Future<void> setPlayhead({required int val}) =>
    RustLib.instance.api.crateApiTransportSetPlayhead(val: val);

Future<void> setLooping({required bool val}) =>
    RustLib.instance.api.crateApiTransportSetLooping(val: val);
